[package]
name = "rsh"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "^0.31.2", features = ["process", "signal", "term", "fs"] }
libc = "0.2"
rustyline = { version = "14", features = ["derive"] }        # readline with history
thiserror = "2"         # error types
signal-hook = "0.3"
uucore   = "0.0.28"
uu_ls = "0.8.0"
uu_cat = "0.8.0"
uu_echo = "0.8.0"
uu_printf = "0.8.0"
uu_cp = "0.8.0"
uu_mv = "0.8.0"
uu_rm = "0.8.0"
uu_mkdir = "0.8.0"
uu_rmdir = "0.8.0"
uu_touch = "0.8.0"
uu_ln = "0.8.0"
uu_chmod = "0.8.0"
uu_chown = "0.8.0"
uu_stat = "0.8.0"
uu_du = "0.8.0"
uu_df = "0.8.0"
uu_install = "0.8.0"
uu_mktemp = "0.8.0"
uu_head = "0.8.0"
uu_tail = "0.8.0"
uu_wc = "0.8.0"
uu_sort = "0.8.0"
uu_uniq = "0.8.0"
uu_cut = "0.8.0"
uu_tr = "0.8.0"
uu_whoami = "0.8.0"
uu_id = "0.8.0"
uu_hostname = "0.8.0"
uu_uname = "0.8.0"
uu_uptime = "0.8.0"
uu_date = "0.8.0"
uu_sleep = "0.8.0"
uu_yes = "0.8.0"
uu_env = "0.8.0"
uu_nohup = "0.8.0"
uu_timeout = "0.8.0"
uu_nice = "0.8.0"
uu_printenv = "0.8.0"
uu_tty = "0.8.0"
uu_stty = "0.8.0"
uu_base32 = "0.8.0"
uu_base64 = "0.8.0"
uu_md5sum = "0.8.0"
uu_sha256sum = "0.8.0"
uu_sha512sum = "0.8.0"
uu_cksum = "0.8.0"
uu_sum = "0.8.0"
uu_b2sum = "0.8.0"
uu_seq = "0.8.0"
uu_factor = "0.8.0"
uu_basename = "0.8.0"
uu_dirname = "0.8.0"
uu_realpath = "0.8.0"
uu_pathchk = "0.8.0"
uu_link = "0.8.0"
uu_unlink = "0.8.0"
uu_sync = "0.8.0"
uu_truncate = "0.8.0"
uu_shuf = "0.8.0"
uu_comm = "0.8.0"
uu_csplit = "0.8.0"
uu_split = "0.8.0"
uu_tee = "0.8.0"
uu_test = "0.8.0"
uu_expr = "0.8.0"
grep = "0.4.1"
findutils = "0.8.0"
uu_paste = "0.8.0"
uu_join = "0.8.0"
uu_fold = "0.8.0"
uu_fmt = "0.8.0"
uu_tac = "0.8.0"
glob = "0.3.3"

